name: GitHub Classroom Workflow - Week13
on:
  push:
    paths:
      - 'chapter13/**'
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  build:
    name: Autograding Week13
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: week13-01-structbasic
        id: week13-01-structbasic
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week13-01-structbasic
          setup-command: gcc chapter13/01structbasic.c -o w1301
          command: ./w1301
          input: ""
          expected-output: "300000.00"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week13-02-nestedstruct
        id: week13-02-nestedstruct
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week13-02-nestedstruct
          setup-command: gcc chapter13/02nestedstruct.c -o w1302
          command: ./w1302
          input: ""
          expected-output: "[2022. 3. 9]"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week13-03-structcmp
        id: week13-03-structcmp
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week13-03-structcmp
          setup-command: gcc chapter13/03structcmp.c -o w1303
          command: ./w1303
          input: "나한국"
          expected-output: "내용이 같은 구조체입니다."
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week13-04-union
        id: week13-04-union
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week13-04-union
          setup-command: gcc chapter13/04union.c -o w1304
          command: ./w1304
          input: ""
          expected-output: "3.780000"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week13-05-typedef
        id: week13-05-typedef
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week13-05-typedef
          setup-command: gcc chapter13/05typedef.c -o w1305
          command: ./w1305
          input: ""
          expected-output: "24500000"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week13-06-tdefstruct
        id: week13-06-tdefstruct
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week13-06-tdefstruct
          setup-command: gcc chapter13/06tdefstruct.c -o w1306
          command: ./w1306
          input: ""
          expected-output: "2022. 8. 29"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week13-07-structptr
        id: week13-07-structptr
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week13-07-structptr
          setup-command: gcc chapter13/07structptr.c -o w1307
          command: ./w1307
          input: ""
          expected-output: "전공필수"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week13-08-unionptr
        id: week13-08-unionptr
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week13-08-unionptr
          setup-command: gcc chapter13/08unionptr.c -o w1308
          command: ./w1308
          input: ""
          expected-output: "3.14"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week13-09-structary
        id: week13-09-structary
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week13-09-structary
          setup-command: gcc chapter13/09structary.c -o w1309
          command: ./w1309
          input: ""
          expected-output: "배열크기: 5"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week13-lab1-structcity
        id: week13-lab1-structcity
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week13-lab1-structcity
          setup-command: gcc chapter13/lab1structcity.c -o w13lab1
          command: ./w13lab1
          input: ""
          expected-output: "[서울]"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week13-lab2-structmovie
        id: week13-lab2-structmovie
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week13-lab2-structmovie
          setup-command: gcc chapter13/lab2structmovie.c -o w13lab2
          command: ./w13lab2
          input: ""
          expected-output: "310000000000"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week13-lab3-boxoffice
        id: week13-lab3-boxoffice
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week13-lab3-boxoffice
          setup-command: gcc chapter13/lab3boxoffice.c -o w13lab3
          command: ./w13lab3
          input: ""
          expected-output: "김용화"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        continue-on-error: true
        env:
          WEEK13-01-STRUCTBASIC_RESULTS: "${{steps.week13-01-structbasic.outputs.result}}"
          WEEK13-02-NESTEDSTRUCT_RESULTS: "${{steps.week13-02-nestedstruct.outputs.result}}"
          WEEK13-03-STRUCTCMP_RESULTS: "${{steps.week13-03-structcmp.outputs.result}}"
          WEEK13-04-UNION_RESULTS: "${{steps.week13-04-union.outputs.result}}"
          WEEK13-05-TYPEDEF_RESULTS: "${{steps.week13-05-typedef.outputs.result}}"
          WEEK13-06-TDEFSTRUCT_RESULTS: "${{steps.week13-06-tdefstruct.outputs.result}}"
          WEEK13-07-STRUCTPTR_RESULTS: "${{steps.week13-07-structptr.outputs.result}}"
          WEEK13-08-UNIONPTR_RESULTS: "${{steps.week13-08-unionptr.outputs.result}}"
          WEEK13-09-STRUCTARY_RESULTS: "${{steps.week13-09-structary.outputs.result}}"
          WEEK13-LAB1-STRUCTCITY_RESULTS: "${{steps.week13-lab1-structcity.outputs.result}}"
          WEEK13-LAB2-STRUCTMOVIE_RESULTS: "${{steps.week13-lab2-structmovie.outputs.result}}"
          WEEK13-LAB3-BOXOFFICE_RESULTS: "${{steps.week13-lab3-boxoffice.outputs.result}}"
        with:
          runners: week13-01-structbasic,week13-02-nestedstruct,week13-03-structcmp,week13-04-union,week13-05-typedef,week13-06-tdefstruct,week13-07-structptr,week13-08-unionptr,week13-09-structary,week13-lab1-structcity,week13-lab2-structmovie,week13-lab3-boxoffice
