name: GitHub Classroom Workflow - Week07
on:
  push:
    paths:
      - 'chapter07/**'
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  build:
    name: Autograding Week07
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: week07-03-whilebasic
        id: week07-03-whilebasic
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week07-03-whilebasic
          setup-command: gcc chapter07/03whilebasic.c -o w703
          command: ./w703
          input: ""
          expected-output: "제어 변수 count => 4"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week07-04-whilenum
        id: week07-04-whilenum
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week07-04-whilenum
          setup-command: gcc chapter07/04whilenum.c -o w704
          command: ./w704
          input: |-
            1.5
            2.3
            0
          expected-output: "합 = 3.80"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week07-05-dowhile
        id: week07-05-dowhile
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week07-05-dowhile
          setup-command: gcc chapter07/05dowhile.c -o w705
          command: ./w705
          input: |-
            1
            0
          expected-output: "[0]종료 [1]아메리카노 [2]카페라떼 [3]카푸치노"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week07-06-forbasic
        id: week07-06-forbasic
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week07-06-forbasic
          setup-command: gcc chapter07/06forbasic.c -o w706
          command: ./w706
          input: ""
          expected-output: "for 종료 이후 i => 6"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week07-07-forcel2far3
        id: week07-07-forcel2far3
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week07-07-forcel2far3
          setup-command: gcc chapter07/07forcel2far3.c -o w707
          command: ./w707
          input: ""
          expected-output: "32.46    90.43"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week07-08-forintbit
        id: week07-08-forintbit
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week07-08-forintbit
          setup-command: gcc chapter07/08forintbit.c -o w708
          command: ./w708
          input: ""
          expected-output: "00000000000000000000000000001101"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week07-09-forsum
        id: week07-09-forsum
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week07-09-forsum
          setup-command: gcc chapter07/09forsum.c -o w709
          command: ./w709
          input: ""
          expected-output: "1 ~ 10 합: 55"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week07-10-inputsum
        id: week07-10-inputsum
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week07-10-inputsum
          setup-command: gcc chapter07/10inputsum.c -o w710
          command: ./w710
          input: "10"
          expected-output: "while 문으로 구한 1에서 10까지 합:  55"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week07-11-break
        id: week07-11-break
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week07-11-break
          setup-command: gcc chapter07/11break.c -o w711
          command: ./w711
          input: |-
            15
            0
          expected-output: "입력한 정수 15: 16진수 0xf"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week07-12-continue
        id: week07-12-continue
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week07-12-continue
          setup-command: gcc chapter07/12continue.c -o w712
          command: ./w712
          input: ""
          expected-output: "  1  2  4  5  7  8 10 11 13 14"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week07-13-goto
        id: week07-13-goto
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week07-13-goto
          setup-command: gcc chapter07/13goto.c -o w713
          command: ./w713
          input: ""
          expected-output: "종료"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week07-14-octhex
        id: week07-14-octhex
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week07-14-octhex
          setup-command: gcc chapter07/14octhex.c -o w714
          command: ./w714
          input: |-
            13
            0
          expected-output: "정수 13: 8진수 015  16진수 0xd"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week07-15-nestedloop
        id: week07-15-nestedloop
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week07-15-nestedloop
          setup-command: gcc chapter07/15nestedloop.c -o w715
          command: ./w715
          input: ""
          expected-output: "m = 5"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week07-16-triangle
        id: week07-16-triangle
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week07-16-triangle
          setup-command: gcc chapter07/16triangle.c -o w716
          command: ./w716
          input: ""
          expected-output: "*****"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week07-17-loopsum
        id: week07-17-loopsum
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week07-17-loopsum
          setup-command: gcc chapter07/17loopsum.c -o w717
          command: ./w717
          input: |-
            3
            0
          expected-output: "1 + 2 + 3 = 6"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week07-lab1-max
        id: week07-lab1-max
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week07-lab1-max
          setup-command: gcc chapter07/lab1max.c -o w7lab1
          command: ./w7lab1
          input: |-
            140
            125
            150
            120
            130
            115
          expected-output: "정원 4명 완료!"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week07-lab2-digit
        id: week07-lab2-digit
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week07-lab2-digit
          setup-command: gcc chapter07/lab2digit.c -o w7lab2
          command: ./w7lab2
          input: "456"
          expected-output: "100단위 출력: 4"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week07-lab3-primebreak
        id: week07-lab3-primebreak
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week07-lab3-primebreak
          setup-command: gcc chapter07/lab3primebreak.c -o w7lab3
          command: ./w7lab3
          input: "17"
          expected-output: "17 소수이다."
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: week07-lab4-mtable
        id: week07-lab4-mtable
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: week07-lab4-mtable
          setup-command: gcc chapter07/lab4mtable.c -o w7lab4
          command: ./w7lab4
          input: ""
          expected-output: "    9단 출력"
          comparison-method: contains
          timeout: 10
          max-score: 10

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        continue-on-error: true
        env:
          WEEK07-03-WHILEBASIC_RESULTS: "${{steps.week07-03-whilebasic.outputs.result}}"
          WEEK07-04-WHILENUM_RESULTS: "${{steps.week07-04-whilenum.outputs.result}}"
          WEEK07-05-DOWHILE_RESULTS: "${{steps.week07-05-dowhile.outputs.result}}"
          WEEK07-06-FORBASIC_RESULTS: "${{steps.week07-06-forbasic.outputs.result}}"
          WEEK07-07-FORCEL2FAR3_RESULTS: "${{steps.week07-07-forcel2far3.outputs.result}}"
          WEEK07-08-FORINTBIT_RESULTS: "${{steps.week07-08-forintbit.outputs.result}}"
          WEEK07-09-FORSUM_RESULTS: "${{steps.week07-09-forsum.outputs.result}}"
          WEEK07-10-INPUTSUM_RESULTS: "${{steps.week07-10-inputsum.outputs.result}}"
          WEEK07-11-BREAK_RESULTS: "${{steps.week07-11-break.outputs.result}}"
          WEEK07-12-CONTINUE_RESULTS: "${{steps.week07-12-continue.outputs.result}}"
          WEEK07-13-GOTO_RESULTS: "${{steps.week07-13-goto.outputs.result}}"
          WEEK07-14-OCTHEX_RESULTS: "${{steps.week07-14-octhex.outputs.result}}"
          WEEK07-15-NESTEDLOOP_RESULTS: "${{steps.week07-15-nestedloop.outputs.result}}"
          WEEK07-16-TRIANGLE_RESULTS: "${{steps.week07-16-triangle.outputs.result}}"
          WEEK07-17-LOOPSUM_RESULTS: "${{steps.week07-17-loopsum.outputs.result}}"
          WEEK07-LAB1-MAX_RESULTS: "${{steps.week07-lab1-max.outputs.result}}"
          WEEK07-LAB2-DIGIT_RESULTS: "${{steps.week07-lab2-digit.outputs.result}}"
          WEEK07-LAB3-PRIMEBREAK_RESULTS: "${{steps.week07-lab3-primebreak.outputs.result}}"
          WEEK07-LAB4-MTABLE_RESULTS: "${{steps.week07-lab4-mtable.outputs.result}}"
        with:
          runners: week07-03-whilebasic,week07-04-whilenum,week07-05-dowhile,week07-06-forbasic,week07-07-forcel2far3,week07-08-forintbit,week07-09-forsum,week07-10-inputsum,week07-11-break,week07-12-continue,week07-13-goto,week07-14-octhex,week07-15-nestedloop,week07-16-triangle,week07-17-loopsum,week07-lab1-max,week07-lab2-digit,week07-lab3-primebreak,week07-lab4-mtable
